version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/wp-content/themes/your-theme-folder
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass